### PR TITLE
Adding the electricity consumption (mle) slides

### PR DESCRIPTION
**Pull request by Madhav-Kanda**
The last slide contains the MLE fit for the poor data on electricity consumption. I have a query about how we can use the MLE obtained from Hostel A (good data) in the case of Hostel B (poor data) as prior. One way could be to use it as the mean for the normal prior distribution that we will consider for Hostel B's dataset and assume some std but I am not entirely sure whether I should go ahead with it or not.

### CODE REVIEW

**Comment by patel-zeel** [comment]
Figures can live in a single folder /figures/introduction.

**Comment by Madhav-Kanda** [comment]
> Figures can live in a single folder /figures/introduction.

I don't exactly recall but maybe we discussed with sir to keep them in separate folders in case of some merge conflicts later.

**Comment by patel-zeel** [comment]
Can you make sure, your commit doesn't affect `introduction.pdf`?

**Comment by Madhav-Kanda** [comment]
> Can you make sure, your commit doesn't affect `introduction.pdf`?

Yes, it won't affect `introduction.pdf`.

**Comment by nipunbatra** [comment]
Though I have merged this, I have a few comments:

1. Do not use the grid
2. x-label should be Number of Occupants 
3. y-label should be Electricity consumption (kWh)
4. No need for title in figures
5. The "Data" figure can perhaps have a few more datapoints
6. When we should some potential fits: we need to have them labelled as: A (\theta_0 = .., \theta_1 = ..). So, add a legend
7. MLE-GD is a confusing term. We can say: Least Squares; or just MLE


and so on..

**Pull request merged**
